# Generated by Django 5.2.6 on 2025-09-27 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=datetime.datetime(2025, 9, 27, 7, 25, 36, 733967, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
