# Generated by Django 5.2.6 on 2025-10-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cashbook_current_balance_cashbook_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
